# Generated by Django 6.0.3 on 2026-03-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electronics', 'Elekronikalar'), ('clothes', 'Kiyimlar'), ('accessories', 'Aksessuarlar'), ('livelihood', "Uy ro'zg'ori")], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image/')),
                ('about', models.TextField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('comment', models.TextField(max_length=500)),
                ('estimating', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=10)),
                ('size', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('favourite', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
