# Generated by Django 6.0.3 on 2026-03-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_created_at_users_upgraded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
