# Generated by Django 6.0.3 on 2026-03-29 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_order', models.CharField(choices=[('delivery_point', 'Yetkazib berish punkti'), ('curier', 'Kuryer')], default='curier', max_length=25)),
                ('address', models.TextField(verbose_name=500)),
                ('arrives_at', models.DateTimeField()),
                ('payment_type', models.CharField(choices=[('with_card', 'Karta orqali'), ('received_the_order', 'Buyurtmani qabul qilganda')], default='received_the_order', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_orders', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('formalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.formalization')),
            ],
        ),
    ]
